# fly.toml app configuration file generated for cdumas-family-chores on 2023-09-10T00:31:39-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cdumas-family-chores"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
